#!/usr/bin/env zsh

PLUGIN_DIR="$HOME/.config/sketchybar/plugins-laptop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

sketchybar --bar \
  height=38 \
  color=0x00000000 \
  margin=0 \
  sticky=on \
  padding_left=16 \
  padding_right=8 \
  notch_width=228 \
  blur_radius=40

# Alternatiive background colors
# label.color=0xffffffff
# background.color=0x9924273a
sketchybar --default \
  background.corner_radius=5 \
  background.padding_right=5 \
  background.height=26 \
  icon.font="Hack Nerd Font:Bold:16.0" \
  label.font="SF Pro:Semibold:16.0" \
  icon.padding_left=5 \
  icon.padding_right=5 \
  icon.color=0xFFFFFFFF \
  label.font="SF Pro:Semibold:14.0" \
  label.color=0xFFFFFFFF \
  label.y_offset=0 \
  label.padding_left=0 \
  label.padding_right=5

# Add the aerospace_workspace_change event we specified in aerospace.toml
sketchybar --add event aerospace_workspace_change
sketchybar --add event aerospace_mode_change
# sketchybar --add event spotify_change $SPOTIFY_EVENT

sketchybar --add item aerospace_mode e \
  --subscribe aerospace_mode aerospace_mode_change \
  --set aerospace_mode \
  drawing=off \
  background.drawing=on \
  background.border_color=0xAAFFFFFF \
  background.border_width=1 \
  icon.drawing=off \
  icon.padding_left=0 \
  icon.padding_right=0 \
  label="M" \
  label.padding_left=8 \
  label.padding_right=9 \
  script="$PLUGIN_SHARED_DIR/aerospace.sh" \
  label.drawing=yes

# sketchybar --add item spotify e \
#   --set spotify \
#   icon= \
#   icon.y_offset=1 \
#   label.drawing=off \
#   label.padding_left=3 \
#   script="$PLUGIN_DIR/spotify.sh" \
#   --subscribe spotify spotify_change mouse.clicked

# This only works for single monitor configs!
for sid in $(aerospace list-workspaces --all); do
  #for sid in "${SPACE_IDS[@]}"; do
  sketchybar --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change \
    --set space.$sid \
    drawing=off \
    background.drawing=on \
    background.border_color=0xAAFFFFFF \
    background.border_width=1 \
    background.height=24 \
    icon="$sid" \
    icon.padding_left=10 \
    icon.padding_right=0 \
    icon.color=0xAAFFFFFF \
    icon.font="SF Pro:Semibold:14.0" \
    label.font="sketchybar-app-font:Regular:12.0" \
    label.padding_right=20 \
    label.padding_left=0 \
    label.y_offset=-1 \
    label.color=0xAAFFFFFF \
    click_script="aerospace workspace $sid" \
    script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

# Load Icons on startup
for sid in $(aerospace list-workspaces --all); do
  apps=$(aerospace list-windows --workspace "$sid" | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')

  icon_strip=" "
  if [ "${apps}" != "" ]; then
    sketchybar --set space.$sid drawing=on

    while read -r app; do
      icon_strip+=" $($CONFIG_DIR/plugins/icon_map_fn.sh "$app")"
    done <<<"${apps}"
  else
    icon_strip=""
  fi
  sketchybar --set space.$sid label="$icon_strip"
done

focused_workspace=$(aerospace list-workspaces --focused)
sketchybar --set space.$focused_workspace background.border_width=2 background.border_color=0xFFFFFFFF icon.color=0xFFFFFFFF label.color=0xFFFFFFFF

sketchybar --add item space_separator left \
  --set space_separator icon="" \
  icon.padding_left=4 \
  label.drawing=off \
  background.drawing=off \
  script="$PLUGIN_SHARED_DIR/space_windows.sh" \
  --subscribe space_separator aerospace_workspace_change space_windows_change system_woke

sketchybar --add item front_app left \
  --set front_app \
  background.padding_left=0 \
  background.padding_right=0 \
  icon.drawing=off \
  icon.padding_left=0 \
  icon.padding_right=0 \
  icon.font="sketchybar-app-font:Regular:14.0" \
  label.padding_left=0 \
  label.padding_right=0 \
  script="$PLUGIN_SHARED_DIR/front_app.sh" \
  label.drawing=yes

sketchybar --add item weather.moon q \
  --set weather.moon \
  background.padding_right=-1 \
  icon.padding_left=4 \
  icon.padding_right=3 \
  label.drawing=off \
  --subscribe weather.moon mouse.clicked

sketchybar --add item weather q \
  --set weather \
  icon= \
  update_freq=1800 \
  script="$PLUGIN_SHARED_DIR/weather.sh" \
  --subscribe weather system_woke

sketchybar --add bracket front_app_bracket \
  front_app \
  front_app.separator \
  front_app.name \
  --subscribe front_app front_app_switched

sketchybar --add item clock right \
  --set clock \
  icon=󰃰 \
  update_freq=60 \
  script="$PLUGIN_SHARED_DIR/clock.sh"

sketchybar --add item battery right \
  --set battery \
  update_freq=20 \
  script="$PLUGIN_DIR/battery.sh"

sketchybar --add item volume right \
  --set volume \
  label.drawing=true \
  script="$PLUGIN_SHARED_DIR/volume.sh" \
  --subscribe volume volume_change

sketchybar --add item wifi right \
  --set wifi script="$PLUGIN_SHARED_DIR/wifi.sh" \
  update_freq=60

# osascript -e 'quit app "Rectangle"'
# open -a Rectangle

##### Finalizing Setup #####
sketchybar --hotload on
sketchybar --update
sketchybar --trigger space_change
